[package]
name = "src-graph"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-src-graph"
path = "src/main.rs"

[[bin]]
name = "src-graph-driver"
path = "src/driver.rs"

[dependencies]

[package.metadata.rust-analyzer]
rustc_private = true
